DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 4
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]


OPTIM:
  NAME: "adam"
  LR: 0.002
  MAX_EPOCH: 20
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 5
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20
  EARLY_STOPPING: True
  PATIENT_COUNT: 3

MODEL:
  INIT_SEED: 2023
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  BITP:
    N_CTX: 1
    CTX_INIT: "a photo of a"
    PREC: "fp16"
    PROMPT_DEPTH: 9
    CONNECT_METHOD: "joint"

TEST:
  NO_TEST: False
  FINAL_MODEL: "best_val"

SHARE:
  SHARE_PARAMETER_VISUAL: True
  SHARE_PARAMETER_TEXT: True



