DATASET:
  NAME: "StanfordCars"

# OPTIM:
#   NAME: "adam"
#   LR: 0.002
#   MAX_EPOCH: 15
#   LR_SCHEDULER: "cosine"
#   WARMUP_EPOCH: 5
#   WARMUP_TYPE: "constant"
#   WARMUP_CONS_LR: 1e-5

# TRAIN:
#   PRINT_FREQ: 20
#   EARLY_STOPPING: True
#   PATIENT_COUNT: 3
