DATASET:
  NAME: "UCF101"

# OPTIM:
#   NAME: "adam"
#   LR: 0.0022
#   MAX_EPOCH: 20
#   LR_SCHEDULER: "cosine"
#   WARMUP_EPOCH: 4
#   WARMUP_TYPE: "constant"
#   WARMUP_CONS_LR: 1e-5

# TRAIN:
#   PRINT_FREQ: 20
#   EARLY_STOPPING: True
#   PATIENT_COUNT: 3